Project : Admission Department Student
Admission : Admission.c
	g++ -o Admission Admission.c -lsocket -lnsl -lresolv
Department : Department.c
	g++ -o Department Department.c -lsocket -lnsl -lresolv
Student : Student.c
	g++ -o Student Student.c -lsocket -lnsl -lresolv
clean :
	rm -f Admission Department Student
